server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wolfcode_goods?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 150201
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    validationQuery: select 'x'

mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true    #驼峰映射
